/* eslint-disable import/prefer-default-export */
export const TVSHOWS_LOAD_PENDING = 'TVSHOWS_LOAD_PENDING';
export const TVSHOWS_LOAD_SUCCESS = 'TVSHOWS_LOAD_SUCCESS';
export const TVSHOWS_LOAD_FAIL = 'TVSHOWS_LOAD_FAIL';

export const TVSHOW_DETAIL_LOAD_PENDING = 'TVSHOW_DETAIL_LOAD_PENDING';
export const TVSHOW_DETAIL_LOAD_SUCCESS = 'TVSHOW_DETAIL_LOAD_SUCCESS';
export const TVSHOW_DETAIL_LOAD_FAIL = 'TVSHOW_DETAIL_LOAD_FAIL';

export const SEASON_LOAD_PENDING = 'SEASON_LOAD_PENDING';
export const SEASON_LOAD_SUCCESS = 'SEASON_LOAD_SUCCESS';
export const SEASON_LOAD_FAIL = 'SEASON_LOAD_FAIL';
